#!/usr/bin/env php
<?php

declare(strict_types=1);

require_once __DIR__ . '/../../../src/Enums/RegionEnum.php';

use Narsil\Skills\Enums\RegionEnum;

$files = [];

foreach (array_slice($argv, 1) as $path)
{
    if (is_dir($path))
    {
        $excludedDirectories = array_values(array_filter([
            realpath($path . DIRECTORY_SEPARATOR . 'vendor'),
            realpath($path . DIRECTORY_SEPARATOR . 'node_modules'),
        ]));
        $iterator = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($path, FilesystemIterator::SKIP_DOTS));

        foreach ($iterator as $file)
        {
            $realPath = realpath($file->getPathname()) ?: $file->getPathname();

            if ($file->isFile() && $file->getExtension() === 'php' && !str_ends_with($realPath, '.blade.php') && !array_filter($excludedDirectories, static function (string $excludedDirectory) use ($realPath): bool
            {
                return str_starts_with($realPath, $excludedDirectory . DIRECTORY_SEPARATOR);
            }))
            {
                $files[] = $file->getPathname();
            }
        }

        continue;
    }

    if (is_file($path))
    {
        $files[] = $path;
    }
}

$sortableRegions = [
    RegionEnum::CONSTANTS->value,
    RegionEnum::PROPERTIES->value,
];

foreach (array_values(array_unique($files)) as $file)
{
    $contents = (string)file_get_contents($file);
    $originalContents = $contents;
    $tokens = token_get_all($contents);
    $offsets = [];
    $offset = 0;

    foreach ($tokens as $index => $token)
    {
        $offsets[$index] = $offset;
        $offset += strlen(is_array($token) ? $token[1] : $token);
    }

    $braceDepth = 0;
    $classDepth = null;
    $classBodyDepth = null;
    $classOpening = null;
    $classClosing = null;
    $classCount = 0;
    $tokenCount = count($tokens);

    foreach ($tokens as $index => $token)
    {
        $id = is_array($token) ? $token[0] : null;
        $text = is_array($token) ? $token[1] : $token;

        if (in_array($id, [T_CLASS, T_ENUM, T_INTERFACE, T_TRAIT], true))
        {
            $classCount++;
            $next = $index + 1;

            while ($next < $tokenCount && is_array($tokens[$next]) && $tokens[$next][0] !== T_STRING)
            {
                $next++;
            }

            if (!isset($tokens[$next]))
            {
                continue;
            }

            for ($opening = $next + 1; $opening < $tokenCount; $opening++)
            {
                if (($tokens[$opening] ?? null) === '{')
                {
                    $classDepth = $braceDepth + 1;
                    $classBodyDepth = $classDepth;
                    $classOpening = $opening;

                    break;
                }
            }
        }

        if ($text === '{')
        {
            $braceDepth++;
        }

        if ($text !== '}' || $classDepth === null || $braceDepth !== $classDepth)
        {
            if ($text === '}')
            {
                $braceDepth--;
            }

            continue;
        }

        $classClosing = $index;
        $classDepth = null;
        $braceDepth--;
    }

    if ($classCount !== 1 || $classOpening === null || $classClosing === null)
    {
        continue;
    }

    $braceDepth = 0;
    $region = null;
    $inClass = false;
    $membersByRegion = [];

    foreach ($tokens as $index => $token)
    {
        $id = is_array($token) ? $token[0] : null;
        $text = is_array($token) ? $token[1] : $token;

        if ($index === $classOpening)
        {
            $inClass = true;
        }

        if ($inClass && $id === T_COMMENT)
        {
            if (preg_match('/^#region\s+(.+)$/', trim($text), $matches) === 1)
            {
                $region = trim($matches[1]);
            }
            elseif (trim($text) === '#endregion')
            {
                $region = null;
            }
        }

        if ($text === '{')
        {
            $braceDepth++;
        }

        if ($text === '}')
        {
            $braceDepth--;
        }

        if (!$inClass || $braceDepth !== $classBodyDepth || !in_array($region, $sortableRegions, true) || !in_array($id, [T_CONST, T_VARIABLE], true))
        {
            continue;
        }

        $startToken = $index;

        for ($startIndex = $index - 1; $startIndex > $classOpening; $startIndex--)
        {
            $previous = $tokens[$startIndex];
            $previousId = is_array($previous) ? $previous[0] : null;
            $previousText = is_array($previous) ? $previous[1] : $previous;

            if ($previousId === T_DOC_COMMENT)
            {
                $startToken = $startIndex;

                break;
            }

            if (in_array($previousText, [';', '{', '}'], true) || ($previousId === T_COMMENT && in_array(trim($previousText), ['#region ' . $region, '#endregion'], true)))
            {
                break;
            }

            if ($previousId !== T_WHITESPACE)
            {
                $startToken = $startIndex;
            }
        }

        $name = $id === T_VARIABLE ? $token[1] : '';

        for ($lookAhead = $index + 1; $lookAhead < $tokenCount && $id === T_CONST; $lookAhead++)
        {
            $lookAheadToken = $tokens[$lookAhead];
            $lookAheadId = is_array($lookAheadToken) ? $lookAheadToken[0] : null;

            if (($id === T_CONST && $lookAheadId === T_STRING) || ($id === T_VARIABLE && $lookAheadId === T_VARIABLE))
            {
                $name = $lookAheadToken[1];

                break;
            }
        }

        $endToken = null;

        for ($lookAhead = $index + 1; $lookAhead < $tokenCount; $lookAhead++)
        {
            $lookAheadToken = $tokens[$lookAhead];
            $lookAheadText = is_array($lookAheadToken) ? $lookAheadToken[1] : $lookAheadToken;

            if ($lookAheadText === ';')
            {
                $endToken = $lookAhead;

                break;
            }
        }

        if ($name === '' || $endToken === null)
        {
            continue;
        }

        $membersByRegion[$region][] = [
            'end' => $offsets[$endToken] + strlen(is_array($tokens[$endToken]) ? $tokens[$endToken][1] : $tokens[$endToken]),
            'name' => ltrim($name, '$'),
            'start' => $offsets[$startToken],
        ];
    }

    $replacements = [];

    foreach ($membersByRegion as $members)
    {
        if (count($members) < 2)
        {
            continue;
        }

        for ($memberIndex = 1; $memberIndex < count($members); $memberIndex++)
        {
            if (trim(substr($contents, $members[$memberIndex - 1]['end'], $members[$memberIndex]['start'] - $members[$memberIndex - 1]['end'])) !== '')
            {
                continue 2;
            }
        }

        $sortedMembers = $members;
        usort($sortedMembers, static function (array $first, array $second): int
        {
            return strcasecmp($first['name'], $second['name']);
        });

        if (array_column($members, 'name') === array_column($sortedMembers, 'name'))
        {
            continue;
        }

        $lineStart = strrpos(substr($contents, 0, $members[0]['start']), PHP_EOL);
        $lineStart = $lineStart === false ? 0 : $lineStart + strlen(PHP_EOL);
        $indent = preg_replace('/\S.*/', '', substr($contents, $lineStart, $members[0]['start'] - $lineStart)) ?? '';
        $chunks = [];

        foreach ($sortedMembers as $member)
        {
            $chunks[] = $indent . trim(substr($contents, $member['start'], $member['end'] - $member['start']));
        }

        $replacements[] = [
            'end' => $members[count($members) - 1]['end'],
            'start' => $lineStart,
            'value' => implode(PHP_EOL . PHP_EOL, $chunks),
        ];
    }

    foreach (array_reverse($replacements) as $replacement)
    {
        $contents = substr_replace($contents, $replacement['value'], $replacement['start'], $replacement['end'] - $replacement['start']);
    }

    if ($replacements !== [])
    {
        file_put_contents($file, $contents);
        $syntaxOutput = [];
        $syntaxStatus = 0;
        exec('php -l ' . escapeshellarg($file) . ' 2>&1', $syntaxOutput, $syntaxStatus);

        if ($syntaxStatus !== 0)
        {
            file_put_contents($file, $originalContents);
        }
    }
}
