#!/usr/bin/env php
<?php

declare(strict_types=1);

$scriptDirectory = __DIR__;
$arguments = array_slice($argv, 1);
$command = escapeshellarg($scriptDirectory . '/fix-method-order');

if ($arguments !== [])
{
    $command .= ' ' . implode(' ', array_map('escapeshellarg', $arguments));
}

passthru($command, $status);

exit($status);
