#!/usr/bin/env php
<?php

declare(strict_types=1);

if (!is_file('composer.json'))
{
    printf("FAIL composer: composer.json not found in current directory.\n");

    exit(1);
}

$arguments = 'dump-autoload --no-interaction';

if (!is_file('artisan'))
{
    $arguments .= ' --no-scripts';
}

$output = [];
$status = 0;

exec('composer ' . $arguments . ' 2>&1', $output, $status);

if ($status === 0)
{
    exit(0);
}

printf("FAIL composer: composer %s\n%s\n", $arguments, implode(PHP_EOL, $output));

exit(1);
